# Generated by Django 4.1.3 on 2022-12-04 23:33

import django.core.validators
from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(default=0, max_length=50, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='endbairro',
            field=models.CharField(default=0, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='endcep',
            field=models.CharField(default=0, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='endcidade',
            field=models.CharField(default=0, max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='endcomplemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='medico',
            name='endlogradouro',
            field=models.CharField(default=0, max_length=200, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='endnumero',
            field=models.CharField(default=0, max_length=4, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='enduf',
            field=models.CharField(default=0, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='nacionalidade',
            field=models.CharField(default=0, max_length=50, verbose_name='Nacionalidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('MAS', 'Maculino'), ('FEM', 'Feminino')], default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                        '+99 99 9999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
