# Generated by Django 4.1.3 on 2022-12-02 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=200, verbose_name='Plano')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.planosaude'),
            preserve_default=False,
        ),
    ]
