# Generated by Django 4.1.3 on 2022-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_planosaude_cliente_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endbairro',
            field=models.CharField(default=1, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endcep',
            field=models.CharField(default=1, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endcidade',
            field=models.CharField(default=1, max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endcomplemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endlogradouro',
            field=models.CharField(default=1, max_length=200, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endnumero',
            field=models.CharField(default=1, max_length=4, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='enduf',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(default=0, max_length=50, verbose_name='Nacionalidade'),
            preserve_default=False,
        ),
    ]
